# BÀI TẬP: TITANIC
**Nguồn:** kaggle.com/c/titanic (891 dòng)

In [2]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [3]:
# TODO
print('Số hàng:', df.shape[0], 'Số cột:', df.shape[1])
print()
print('Columns:',df.columns.tolist())
print()
print('Data types:', df.dtypes)

Số hàng: 891 Số cột: 15

Columns: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

Data types: survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [4]:
# TODO
missing = df.isnull().sum()
print("Missing values:")
print(missing[missing>0] if missing.sum()>0 else "Không có cột nào thiếu dữ liệu.")
print()
print('Duplicate values:', df.duplicated().sum())

Missing values:
age            177
embarked         2
deck           688
embark_town      2
dtype: int64

Duplicate values: 107

## A.3. Invalid values

In [5]:
# TODO
print("AGE < 0:", (df['age'] < 0).sum())
print("FARE < 0:", (df['fare'] < 0).sum())
print("PCLASS ngoài [1, 2, 3]:", ((df['pclass'] < 1) | (df['pclass'] > 3)).sum())
print("SURVIVED ngoài [0, 1]:", ((df['survived'] < 0) | (df['survived'] > 1)).sum())
print()
print("Dữ liệu đã được kiểm tra tính hợp lý.")

AGE < 0: 0
FARE < 0: 0
PCLASS ngoài [1, 2, 3]: 0
SURVIVED ngoài [0, 1]: 0

Dữ liệu đã được kiểm tra tính hợp lý.

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [7]:
# TODO
df['family_size'] = df['sibsp'] + df['parch'] + 1
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [8]:
# TODO
for col in ['age', 'fare','survived', 'pclass', 'parch', 'sibsp']: 
    s = df[col].dropna() 
    mean, median, mode = s.mean(), s.median(), s.mode()[0]
    print(f"{col.upper()}: Mean={mean:.2f}, Median={median:.2f}, Mode={mode:.2f}")
print()
print("Mode pclass:", df['pclass'].mode()[0])
print("Mode embarked:", df['embarked'].mode()[0])

AGE: Mean=29.70, Median=28.00, Mode=24.00
FARE: Mean=32.20, Median=14.45, Mode=8.05
SURVIVED: Mean=0.38, Median=0.00, Mode=0.00
PCLASS: Mean=2.31, Median=3.00, Mode=3.00
PARCH: Mean=0.38, Median=0.00, Mode=0.00
SIBSP: Mean=0.52, Median=0.00, Mode=0.00

Mode pclass: 3
Mode embarked: S

## Group 2 — Dispersion

In [9]:
# TODO
for col in ['age', 'fare']:
    s = df[col].dropna()
    range_ = s.max() - s.min()
    std_ = s.std()
    q1, q3 = s.quantile([0.25, 0.75])
    iqr = q3 - q1
    cv = std_ / s.mean()
    print(f"--- {col.upper()} ---")
    print(f"Range={range_:.2f}, Std={std_:.2f}, IQR={iqr:.2f}, CV={cv:.2f}")

--- AGE ---
Range=79.58, Std=14.53, IQR=17.88, CV=0.49
--- FARE ---
Range=512.33, Std=49.69, IQR=23.09, CV=1.54

## Group 3 — Location and Shape

In [10]:
# TODO
for col in ['age', 'fare']:
    s = df[col].dropna()
    skew_, kurt_ = stats.skew(s), stats.kurtosis(s)
    print(f"--- {col.upper()} ---")
    print(f"P25={s.quantile(0.25):.2f}, P50={s.quantile(0.5):.2f}, P75={s.quantile(0.75):.2f}")
    print(f"Skewness={skew_:.2f}, Kurtosis={kurt_:.2f}\n")

--- AGE ---
P25=20.12, P50=28.00, P75=38.00
Skewness=0.39, Kurtosis=0.17

--- FARE ---
P25=7.91, P50=14.45, P75=31.00
Skewness=4.78, Kurtosis=33.20

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [11]:
# TODO
# TODO
tls = (df.groupby('class')['survived'].mean() * 100).sort_values(ascending=False)
print("Tỷ lệ sống sót theo hạng vé (%):")
print(tls.round(2))

chenhlech = tls.max() - tls.min()
print()
print("Chênh lệch tỷ lệ sống sót giữa hạng vé cao nhất và thấp nhất:")
print(chenhlech.round(2), "%")
print()
print("Vé hạng nhất có tỷ lệ sống sót cao nhất, trong khi vé hạng ba có tỷ lệ sống sót thấp nhất.")

Tỷ lệ sống sót theo hạng vé (%):
class
First     62.96
Second    47.28
Third     24.24
Name: survived, dtype: float64

Chênh lệch tỷ lệ sống sót giữa hạng vé cao nhất và thấp nhất:
38.73 %

Vé hạng nhất có tỷ lệ sống sót cao nhất, trong khi vé hạng ba có tỷ lệ sống sót thấp nhất.

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [12]:
# TODO
pivot_titanic = df.pivot_table(
    index='class',      
    columns='sex',     
    values='survived',  
    aggfunc='mean',   
    fill_value=0     
).reset_index()

pivot_titanic[['female', 'male']] = pivot_titanic[['female', 'male']] * 100

print("Bảng tỷ lệ sống sót (%) theo Hạng vé và Giới tính:")
print(pivot_titanic.round(2))
print()
print("Giới tính có ảnh hưởng đến sống sót vì phụ nữ có tỷ lệ sống sót cao hơn nam giới trong cùng hạng vé.")

Bảng tỷ lệ sống sót (%) theo Hạng vé và Giới tính:
sex   class  female   male
0     First   96.81  36.89
1    Second   92.11  15.74
2     Third   50.00  13.54

Giới tính có ảnh hưởng đến sống sót vì phụ nữ có tỷ lệ sống sót cao hơn nam giới trong cùng hạng vé.

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [13]:
# TODO
print(df.groupby("survived")["fare"].mean())
print(df["fare"].corr(df["survived"]))

survived
0    22.117887
1    48.395408
Name: fare, dtype: float64
0.2573065223849622

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [14]:
# TODO
ssgd = df.groupby('family_size')['survived'].mean() * 100
print("Tỷ lệ sống sót theo số lượng người trong gia đình (%):")
print(ssgd.round(2))
print()
print("Những người đi 2 người hoặc đi cùng gia đình nhỏ có tỷ lệ sống sót cao hơn so với những người đi cùng gia đình lớn từ 5 thành viên trở lên.")

Tỷ lệ sống sót theo số lượng người trong gia đình (%):
family_size
1     30.35
2     55.28
3     57.84
4     72.41
5     20.00
6     13.64
7     33.33
8      0.00
11     0.00
Name: survived, dtype: float64

Những người đi 2 người hoặc đi cùng gia đình nhỏ có tỷ lệ sống sót cao hơn so với những người đi cùng gia đình lớn từ 5 thành viên trở lên.

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [15]:
# TODO
# TODO
cang = (df.groupby('embark_town')['survived'].mean() * 100).sort_values(ascending=False)

print("Tỷ lệ sống sót (%) theo Cảng lên tàu:")
print(cang.round(2))
print()

Tỷ lệ sống sót (%) theo Cảng lên tàu:
embark_town
Cherbourg      55.36
Queenstown     38.96
Southampton    33.70
Name: survived, dtype: float64

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

Giới tính: Phụ nữ được ưu tiên cứu hộ tuyệt đối, lấn át mọi yếu tố khác (kể cả hạng vé).

Hạng vé càng cao, giá vé càng đắt thì tỷ lệ sống sót càng lớn.

Gia đình nhỏ (2-4 người) là tối ưu: Dễ hỗ trợ nhau thoát hiểm nhất; đi một mình hoặc đại gia đình đều có rủi ro rất cao.

Cảng Cherbourg có tỷ lệ sống cao thực chất vì đó là nơi đón nhiều hành hạng nhất, chứ không phải do bản thân cái cảng.